### ISSUE TITLE
There is no copyright associated with this project

### ISSUE THREAD

**Issue by leopoldodonnell** [munkyboy/docker-redsocks#7]
Nice work, but until there is a copyright, the project is toxic - its entirely up to you, but it would be super if you could add one - thx

**Comment by munkyboy** [comment]
added MIT license in https://github.com/munkyboy/docker-redsocks/commit/8eaa39d9c56868a53ac5726ed5e7d6593e83cd7d

**Comment by leopoldodonnell** [comment]
Thanks - a huge help to my team.
